apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: demo
  name: demo-7c9457f5bd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      labels:
        app: a
        version: "1"
    spec:
      containers:
        - image: predic8/servicemesh-demo-a:1
          name: main
