apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: limit-access-to-b
  namespace: demo
spec:
  podSelector:
    matchLabels:
      app: b
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: a
    ports:
    - protocol: TCP
      port: 8080